version: '3.8'

services:
  redis-cluster:
    image: bitnami/redis-cluster:8.0.2
    ports:
      - '6379:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_CLUSTER_CREATOR=yes'
    networks:
      - redis-cluster-network

networks:
  redis-cluster-network:
    external: true
